name: zk-alpha-predator
region: nyc
services:
- name: backend
  dockerfile_path: backend/Dockerfile
  source_dir: backend
  github:
    branch: main
    deploy_on_push: true
    repo: pratikshirodkar/Consensus-AI  # You'll need to update this to your actual repo
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: PYTHONUTF8
    value: "1"
  - key: CDP_API_KEY_NAME
    value: "${CDP_API_KEY_NAME}"
  - key: CDP_API_KEY_SECRET
    value: "${CDP_API_KEY_SECRET}"
  - key: CDP_WALLET_SECRET
    value: "${CDP_WALLET_SECRET}"
  - key: VIRTUALS_API_KEY
    value: "${VIRTUALS_API_KEY}"
